DROP TABLE IF EXISTS WEATHER;

CREATE TABLE weather (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datetime timestamp without time zone,
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    temperature double precision
);
-- GRANT ALL on TABLE weather TO weatheruser;